name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Run gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
