name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  go-fmt:
    name: go-fmt
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Run go fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

  go-test:
    name: go-test
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download && go install

      - name: Build package
        run: go build

      - name: Run go test
        # For now, we run all tests in two parts, first those beginning with letter
        # A-L then those beginning with letter M-Z to side-step a race condition
        # where multiple tests access the same shared /tmp directory.
        # TODO: fix that race condition.
        run: |
          go test -run="Test[A-L]" -v ./lib && \
          go test -run="Test[M-Z]" -v ./lib
